default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

development:
  <<: *default
  database: minisns_development

test:
  <<: *default
  database: minisns_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: minisns_production

  cache:
    <<: *primary_production
    database: minisns_production_cache
    schema_dump: db/cache_schema.rb

  queue:
    <<: *primary_production
    database: minisns_production_queue
    schema_dump: db/queue_schema.rb

  cable:
    <<: *primary_production
    database: minisns_production_cable
    schema_dump: db/cable_schema.rb
